'use strict';
/* ============================================================
   Local GLB asset library.  Every entry is optional: a missing or
   invalid model falls back to the existing procedural mesh.
   ============================================================ */

const MODEL_MANIFEST = {
  'character:infantry': {
    file: 'assets/models/infantry/infantry.gltf', height: 2.35, faceOffset: Math.PI,
  },
  // Quaternius animated characters (CC0). Both contain complete humanoid
  // skeletons, authored locomotion/action clips and recognisable equipment.
  'character:worker': {
    file: 'assets/models/quaternius-characters/Worker.glb',
    height: 2.35, faceOffset: 0,
  },
  'character:soldier': {
    file: 'assets/models/quaternius-characters/CharacterSoldier.glb',
    height: 2.35, faceOffset: 0,
  },

  // Quaternius Downtown City MegaKit (CC0). These are complete textured
  // buildings, not boxes generated by the game. Their shared PBR maps are
  // stored beside the glTF files and reused by all three sizes.
  'city:small':  { file: 'assets/models/quaternius-downtown/Building_Small_1.gltf' },
  'city:medium': { file: 'assets/models/quaternius-downtown/Building_Medium_2_001.gltf' },
  'city:large':  { file: 'assets/models/quaternius-downtown/Building_Large_2.gltf' },

  // Kenney City Kit (CC0) — eighteen architecturally distinct shells. Every
  // civic and economic structure is mapped to its own model below, which is
  // what stops a base from looking like the same house stamped out repeatedly.
  'city:a': { file: 'assets/models/kenney-city/building-a.glb' },
  'city:b': { file: 'assets/models/kenney-city/building-b.glb' },
  'city:c': { file: 'assets/models/kenney-city/building-c.glb' },
  'city:d': { file: 'assets/models/kenney-city/building-d.glb' },
  'city:e': { file: 'assets/models/kenney-city/building-e.glb' },
  'city:f': { file: 'assets/models/kenney-city/building-f.glb' },
  'city:g': { file: 'assets/models/kenney-city/building-g.glb' },
  'city:h': { file: 'assets/models/kenney-city/building-h.glb' },
  'city:i': { file: 'assets/models/kenney-city/building-i.glb' },
  'city:j': { file: 'assets/models/kenney-city/building-j.glb' },
  'city:k': { file: 'assets/models/kenney-city/building-k.glb' },
  'city:l': { file: 'assets/models/kenney-city/building-l.glb' },
  'city:m': { file: 'assets/models/kenney-city/building-m.glb' },
  'city:n': { file: 'assets/models/kenney-city/building-n.glb' },
  'city:skyA': { file: 'assets/models/kenney-city/building-skyscraper-a.glb' },
  'city:skyC': { file: 'assets/models/kenney-city/building-skyscraper-c.glb' },
  'city:skyD': { file: 'assets/models/kenney-city/building-skyscraper-d.glb' },
  'city:skyE': { file: 'assets/models/kenney-city/building-skyscraper-e.glb' },

  // Kenney Suburban Houses + Quaternius Farm Buildings (CC0). These keep
  // homes and farms architecturally distinct from the downtown towers.
  'suburban:a': { file: 'assets/models/kenney-suburban/House_A.glb' },
  'suburban:b': { file: 'assets/models/kenney-suburban/House_B.glb' },
  'suburban:c': { file: 'assets/models/kenney-suburban/House_C.glb' },
  'suburban:d': { file: 'assets/models/kenney-suburban/House_D.glb' },
  'farm:barn': { file: 'assets/models/quaternius-farm/BigBarn.glb' },
  'farm:siloHouse': { file: 'assets/models/quaternius-farm/SiloHouse.glb' },

  // Quaternius Ultimate Stylized Nature (CC0), textured glTF trees.
  'nature:birch1': { file: 'assets/models/quaternius-nature/BirchTree_1.gltf' },
  'nature:birch2': { file: 'assets/models/quaternius-nature/BirchTree_2.gltf' },
  'nature:birch3': { file: 'assets/models/quaternius-nature/BirchTree_3.gltf' },
  'nature:birch4': { file: 'assets/models/quaternius-nature/BirchTree_4.gltf' },
  'nature:birch5': { file: 'assets/models/quaternius-nature/BirchTree_5.gltf' },

  // Quaternius Animated Tanks Pack (CC0). FBX only (no glTF export exists),
  // so these load through FBXLoader. Each has its own baked texture and a
  // Tank_Turret/Tank_Gun pair that is NOT part of the track skeleton —
  // makeTankModel() detaches that pair into a rotatable group at runtime so
  // combat aiming works exactly like every procedural turret in the game.
  'unit:tank0': { file: 'assets/models/quaternius-tanks/Tank.fbx', loader: 'fbx' },
  'unit:tank1': { file: 'assets/models/quaternius-tanks/Tank2.fbx', loader: 'fbx' },
  'unit:tank2': { file: 'assets/models/quaternius-tanks/Tank3.fbx', loader: 'fbx' },
  'unit:tank3': { file: 'assets/models/quaternius-tanks/Tank4.fbx', loader: 'fbx' },

  // Kenney Watercraft Pack (CC0) — modern small hulls. Ships without its
  // colormap image like the Kenney city buildings did, so these get the same
  // box-projected-UV + PBR facade fix (see dressHullIfUntextured).
  'unit:gunboat':  { file: 'assets/models/kenney-watercraft/boat-speed-a.glb', span: 5.6, rotationY: Math.PI },
  'unit:corvette': { file: 'assets/models/kenney-watercraft/boat-tug-a.glb',   span: 7.0, rotationY: Math.PI },

};

const MODELS = {
  loaded: new Map(),
  failed: false,
};

// Consolidate static facade pieces while retaining animated radar/flags and
// transparent glass as separate objects. Called before entity overlays attach.
function batchBuildingGeometry(root) {
  if (!THREE.mergeGeometries) return root;
  root.updateMatrixWorld(true);
  const animated = new Set(Object.values(root.userData).filter(v => v?.isObject3D));
  const groups = new Map();
  root.traverse(o => {
    if (!o.isMesh || o.isSkinnedMesh || Array.isArray(o.material) || o.material.transparent || o.children.length || !o.visible) return;
    for (let parent = o; parent; parent = parent.parent) if (animated.has(parent) || !parent.visible) return;
    const attributes = Object.keys(o.geometry.attributes).sort().join(',');
    const key = `${o.material.uuid}:${o.castShadow}:${o.receiveShadow}:${attributes}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(o);
  });
  for (const pieces of groups.values()) {
    if (pieces.length < 2) continue;
    const geometries = pieces.map(o => {
      const geometry = o.geometry.index ? o.geometry.toNonIndexed() : o.geometry.clone();
      geometry.applyMatrix4(o.matrixWorld);
      return geometry;
    });
    const merged = THREE.mergeGeometries(geometries);
    for (const geometry of geometries) geometry.dispose();
    if (!merged) continue;
    const mesh = new THREE.Mesh(merged, pieces[0].material);
    mesh.castShadow = pieces[0].castShadow; mesh.receiveShadow = pieces[0].receiveShadow;
    mesh.name = 'batched-facade';
    for (const piece of pieces) piece.removeFromParent();
    root.add(mesh);
  }
  return root;
}

function loadModel(loaders, key, cfg) {
  return new Promise(resolve => {
    const isFbx = cfg.loader === 'fbx';
    const loader = isFbx ? loaders.fbx : loaders.gltf;
    if (!loader) { resolve(false); return; }
    loader.load(cfg.file, result => {
      // Normalize FBXLoader's raw Object3D into the same {scene, animations}
      // shape GLTFLoader returns, so every call site can treat MODELS.loaded
      // entries uniformly regardless of source format.
      MODELS.loaded.set(key, isFbx ? { scene: result, animations: result.animations || [] } : result);
      resolve(true);
    }, undefined, err => {
      console.warn(`Optional model failed: ${cfg.file}`, err);
      resolve(false);
    });
  });
}

function preloadModels() {
  if (!THREE.GLTFLoader || !THREE.SkeletonUtils) {
    MODELS.failed = true;
    return Promise.resolve();
  }
  THREE.Cache.enabled = true;
  const manager = new THREE.LoadingManager();
  // Use the same HTML image path as terrain/PBR textures. Some embedded
  // browsers expose ImageBitmap support but return empty glTF texture sources.
  manager.addHandler(/\.(png|jpe?g)(\?.*)?$/i, new THREE.TextureLoader(manager));
  const loaders = { gltf: new THREE.GLTFLoader(manager), fbx: THREE.FBXLoader ? new THREE.FBXLoader(manager) : null };
  const jobs = Object.entries(MODEL_MANIFEST).map(([key, cfg]) => loadModel(loaders, key, cfg));
  return Promise.all(jobs).then(results => { MODELS.failed = results.every(ok => !ok); });
}

function cloneMaterials(root, teamColor, tintAmount = 0.08, surfaceTone = null, seed = 0, assetKey = '') {
  const tint = new THREE.Color(teamColor);
  const tone = surfaceTone ? new THREE.Color(surfaceTone) : null;
  const variation = ((seed * 9301 + 49297) % 233280) / 233280;
  const isBuilding = assetKey.startsWith('building:');
  root.traverse(o => {
    if (!o.isMesh) return;
    o.castShadow = true;
    o.receiveShadow = true;
    const mats = Array.isArray(o.material) ? o.material : [o.material];
    const clones = mats.map(material => {
      const m = material.clone();
      if (m.color) {
        if (tone) m.color.lerp(tone, isBuilding ? 0.9 : 0.72);
        m.color.lerp(tint, tintAmount);
        m.color.offsetHSL(
          (variation - 0.5) * (isBuilding ? 0.085 : 0.045),
          isBuilding ? -0.015 : -0.04,
          (variation - 0.5) * (isBuilding ? 0.16 : 0.10),
        );
        if (isBuilding) m.color.multiplyScalar(0.9);
      }
      if ('roughness' in m) m.roughness = Math.max(0.62, m.roughness ?? 0.75);
      if ('metalness' in m) m.metalness = Math.min(0.16, m.metalness ?? 0);
      if ('envMapIntensity' in m) m.envMapIntensity = 0.38;
      if (m.emissive) {
        m.emissive.multiplyScalar(0.12);
        m.emissiveIntensity = Math.min(m.emissiveIntensity || 0, 0.18);
      }
      return m;
    });
    o.material = Array.isArray(o.material) ? clones : clones[0];
  });
}

/* Clone, orient, ground and normalize an authored model into game scale. */
function makeAssetModel(key, teamColor, seed = 0) {
  const gltf = MODELS.loaded.get(key);
  const cfg = MODEL_MANIFEST[key];
  if (!gltf || !cfg) return null;

  const model = gltf.scene.clone(true);
  cloneMaterials(model, teamColor, key.startsWith('unit:') ? 0.14 : 0.025, cfg.tone, seed, key);
  model.rotation.y = cfg.rotationY || 0;
  model.updateMatrixWorld(true);

  let bounds = new THREE.Box3().setFromObject(model);
  const size = bounds.getSize(new THREE.Vector3());
  let scale = cfg.span / Math.max(size.x, size.z, 0.001);
  if (cfg.maxHeight) scale = Math.min(scale, cfg.maxHeight / Math.max(size.y, 0.001));
  model.scale.setScalar(scale);
  model.updateMatrixWorld(true);

  bounds = new THREE.Box3().setFromObject(model);
  const center = bounds.getCenter(new THREE.Vector3());
  model.position.set(-center.x, -bounds.min.y + (cfg.y || 0), -center.z);

  const root = new THREE.Group();
  root.add(model);
  root.userData.assetModel = true;
  root.userData.assetKey = key;
  return root;
}

/* Preserve the authored colour/material work. Team colour is only a small
   identification accent; multiplying the whole model is what made the old
   infantry look like a dark, unreadable lump. */
function cloneAuthoredMaterials(root, teamColor = null, tintAmount = 0) {
  const tint = teamColor == null ? null : new THREE.Color(teamColor);
  root.traverse(o => {
    if (!o.isMesh) return;
    o.castShadow = true;
    o.receiveShadow = true;
    const mats = Array.isArray(o.material) ? o.material : [o.material];
    const copies = mats.map(src => {
      const m = src.clone();
      const matName = (m.name || '').toLowerCase();
      if (tint && tintAmount && m.color && !matName.includes('skin') && !matName.includes('visor')) {
        m.color.lerp(tint, tintAmount);
      }
      if ('envMapIntensity' in m) m.envMapIntensity = Math.max(0.7, m.envMapIntensity || 0);
      return m;
    });
    o.material = Array.isArray(o.material) ? copies : copies[0];
  });
}

function styleExternalArchitecture(root, kind, seed = 0) {
  const wallPalette = [0xd8c7ad, 0xc5c7bc, 0xb9937d, 0xd9d0bd];
  const roofPalette = [0x583b32, 0x414950, 0x65463a, 0x4b4039];
  const wall = wallPalette[Math.abs(seed) % wallPalette.length];
  const roof = roofPalette[Math.abs(seed + 1) % roofPalette.length];
  const pbr = typeof ARCH_PBR !== 'undefined' ? ARCH_PBR : null;
  root.traverse(o => {
    if (!o.isMesh) return;
    const mats = Array.isArray(o.material) ? o.material : [o.material];
    for (const m of mats) {
      const name = (m.name || '').toLowerCase();
      let family = null;
      if (name.includes('window')) {
        m.color.setHex(0x7192a0);
        if (m.emissive) { m.emissive.setHex(0x182a32); m.emissiveIntensity = 0.16; }
        m.roughness = 0.22; m.metalness = 0.08;
      } else if (name.includes('roof') || name.includes('black')) {
        m.color.setHex(roof); family = 'roof';
      } else if (name.includes('door') || name.includes('brown')) {
        m.color.setHex(0x51382c); m.roughness = 0.78; m.metalness = 0;
      } else if (name.includes('red') || name.includes('default')) {
        m.color.setHex(kind === 'farm' ? 0xb26b55 : wall); family = 'brick';
      } else if (name.includes('border') || name.includes('white') || name.includes('grey')) {
        m.color.setHex(name.includes('white') ? 0xe2ddd2 : 0xaaa79f); family = 'concrete';
      }
      if (family && pbr && pbr[family]) {
        const maps = pbr[family];
        if (maps.diffuse) m.map = maps.diffuse;
        if (maps.normal) { m.normalMap = maps.normal; m.normalScale = new THREE.Vector2(0.32, 0.32); }
        if (maps.roughness) m.roughnessMap = maps.roughness;
        m.roughness = family === 'roof' ? 0.76 : 0.84;
        m.metalness = 0;
      }
      m.needsUpdate = true;
    }
  });
}

function normalizeModel(model, targetSpan = null, targetHeight = null) {
  model.updateMatrixWorld(true);
  let bounds = new THREE.Box3().setFromObject(model);
  const size = bounds.getSize(new THREE.Vector3());
  let scale = 1;
  if (targetSpan) scale = targetSpan / Math.max(size.x, size.z, 0.001);
  if (targetHeight) {
    const byHeight = targetHeight / Math.max(size.y, 0.001);
    scale = targetSpan ? Math.min(scale, byHeight) : byHeight;
  }
  model.scale.multiplyScalar(scale);
  model.updateMatrixWorld(true);
  bounds = new THREE.Box3().setFromObject(model);
  const center = bounds.getCenter(new THREE.Vector3());
  model.position.x -= center.x;
  model.position.y -= bounds.min.y;
  model.position.z -= center.z;
  return bounds.getSize(new THREE.Vector3());
}

/* The candidate list is in PRIORITY order. This used to scan the file and
   return the first clip that appeared in the list, which means the export
   order decided which animation won, not the preference — a soldier asked for
   "Run_Gun, else Run" always got Run, because Run is exported first. */
function animationByName(gltf, candidates) {
  for (const candidate of candidates) {
    const want = candidate.toLowerCase();
    const found = gltf.animations.find(c => {
      const full = c.name.toLowerCase();
      return full === want || full.split('|').pop() === want;
    });
    if (found) return found;
  }
  return null;
}

function addReadableCharacterProp(root, kind, teamColor) {
  const dark = new THREE.MeshStandardMaterial({ color: 0x22272b, roughness: 0.52, metalness: 0.48 });
  const metal = new THREE.MeshStandardMaterial({ color: 0x4b5359, roughness: 0.38, metalness: 0.65 });
  const wood = new THREE.MeshStandardMaterial({ color: 0x68452d, roughness: 0.78 });
  const makeBox = (w, h, d, mat, x, y, z) => {
    const m = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), mat);
    m.position.set(x, y, z); m.castShadow = true; return m;
  };
  const makeTube = (radius, length, mat, x, y, z) => {
    const m = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius, length, 10), mat);
    m.rotation.x = Math.PI / 2; m.position.set(x, y, z); m.castShadow = true; return m;
  };

  const prop = new THREE.Group();
  if (kind === 'marker') {
    // The Toon Shooter soldier already contains properly modelled weapons.
  } else if (kind === 'tool') {
    prop.add(makeBox(0.08, 0.58, 0.08, wood, 0, 0, 0));
    prop.add(makeBox(0.34, 0.13, 0.13, metal, 0, 0.28, 0));
    prop.position.set(0.42, 0.78, 0.05);
    prop.rotation.z = -0.18;
  } else if (kind === 'launcher') {
    prop.add(makeTube(0.11, 1.42, dark, 0, 0, 0));
    prop.add(makeTube(0.15, 0.18, metal, 0, 0, 0.66));
    prop.add(makeTube(0.17, 0.16, metal, 0, 0, -0.66));
    prop.add(makeBox(0.1, 0.28, 0.12, dark, 0, -0.19, 0.18));
    prop.position.set(-0.23, 1.57, 0.06);
    prop.rotation.x = -0.18;
  } else {
    const long = kind === 'sniper';
    const length = long ? 1.58 : 1.18;
    prop.add(makeBox(0.16, 0.2, length * 0.58, dark, 0, 0, 0.08));
    prop.add(makeTube(long ? 0.035 : 0.045, length * 0.52, metal, 0, 0.03, length * 0.48));
    prop.add(makeBox(0.13, 0.23, 0.36, wood, 0, -0.02, -length * 0.34));
    prop.add(makeBox(0.07, 0.25, 0.12, dark, 0, -0.2, -0.02));
    if (long) {
      prop.add(makeTube(0.055, 0.34, dark, 0, 0.15, 0.08));
      prop.children[prop.children.length - 1].rotation.set(0, 0, Math.PI / 2);
    }
    prop.position.set(0.2, 1.34, 0.23);
    prop.rotation.x = -0.16;
  }
  root.add(prop);

  // A small coloured armband stays readable at RTS distance without repainting
  // skin, clothing or weapons.
  if (kind !== 'tool') {
    const band = new THREE.Mesh(
      new THREE.TorusGeometry(0.13, 0.035, 6, 14),
      new THREE.MeshStandardMaterial({ color: teamColor, roughness: 0.5, metalness: 0.08 }),
    );
    band.position.set(-0.29, 1.55, 0); band.rotation.x = Math.PI / 2;
    band.castShadow = true; root.add(band);
  }
}

function selectAuthoredWeapon(model, requested) {
  const weapons = new Set([
    'Revolver', 'Sniper', 'Revolver_Small', 'Pistol', 'SMG',
    'GrenadeLauncher', 'ShortCannon', 'Shotgun', 'Sniper_2',
    'RocketLauncher', 'AK', 'Shovel', 'Knife_2', 'Knife_1',
  ]);
  const chosen = requested === 'launcher' ? 'RocketLauncher'
    : requested === 'sniper' ? 'Sniper_2' : 'AK';
  model.traverse(o => {
    if (weapons.has(o.name)) o.visible = o.name === chosen;
  });
}

function makeCharacterRig(character, teamColor, opts = {}) {
  const key = `character:${character}`;
  const gltf = MODELS.loaded.get(key);
  const cfg = MODEL_MANIFEST[key];
  if (!gltf || !cfg) return null;
  let model;
  try { model = THREE.SkeletonUtils.clone(gltf.scene); }
  catch (e) { return null; }

  const g = new THREE.Group();
  if (character === 'soldier') selectAuthoredWeapon(model, opts.weapon);
  cloneAuthoredMaterials(model, teamColor, character === 'soldier' ? 0.055 : 0.025);
  // TEAM COLOUR. Ownership used to be communicated by a 13 cm armband, which at
  // the distance an RTS camera actually sits at is one invisible pixel — so
  // every soldier of every nation read as the same brown figure. The uniform
  // itself now carries the nation's colour, knocked back toward field green so
  // it still looks like a uniform rather than fancy dress. Skin, weapons and
  // webbing are deliberately left alone: the point is a readable colour, not a
  // repainted character.
  if (character === 'soldier' || character === 'worker') {
    const team = new THREE.Color(teamColor);
    const tunic = team.clone().lerp(new THREE.Color(0x6a7358), 0.78);
    const trousers = team.clone().lerp(new THREE.Color(0x3f4436), 0.88);
    model.traverse(o => {
      if (!o.isMesh) return;
      for (const m of Array.isArray(o.material) ? o.material : [o.material]) {
        const name = (m.name || '').toLowerCase();
        if (/skin|character_main|pants|worker_vest|brown2?$/.test(name)) {
          m.metalness = 0; m.roughness = .86;
          // Character_Main = soldier tunic, Worker_Vest = the worker's hi-vis,
          // Brown/Brown2 = the worker's shirt and trousers
          if (name === 'character_main' || name === 'worker_vest' || name === 'brown') m.color.copy(tunic);
          if (name === 'pants' || name === 'brown2') m.color.copy(trousers);
        } else { m.metalness = .18; m.roughness = .58; }
      }
    });
  }
  normalizeModel(model, null, opts.height || cfg.height || 2.3);
  model.rotation.y = opts.rotationY || 0;
  g.add(model);
  if (character !== 'infantry') addReadableCharacterProp(g, character === 'worker' ? 'tool' : 'marker', teamColor);

  const mixer = new THREE.AnimationMixer(model);
  const clips = character === 'worker' ? {
    idle: ['Idle_Neutral', 'Idle'], walk: ['Walk'], run: ['Run'],
    work: ['Interact', 'Punch'],
  } : {
    // a weapon-ready stance when halted, and the gun-up run while advancing —
    // soldiers should never look like they are out for a jog
    idle: ['Idle_Gun', 'Idle_Neutral', 'Idle'],
    walk: ['Walk', 'Run_Gun', 'Run'],
    run: ['Run_Gun', 'Run'],
    shoot: ['Idle_Shoot', 'Idle_Gun_Shoot', 'Gun_Shoot'],
  };
  const actions = {};
  for (const [name, candidates] of Object.entries(clips)) {
    const c = animationByName(gltf, candidates);
    if (!c) continue;
    const action = mixer.clipAction(c);
    action.enabled = true;
    action.setEffectiveWeight(name === 'idle' ? 1 : 0);
    action.play();
    actions[name] = action;
  }
  mixer.update(Math.random() * 2);
  g.userData.mixer = mixer;
  g.userData.actions = actions;
  g.userData.faceOffset = cfg.faceOffset || 0;
  g.userData.characterModel = character;
  return g;
}

/* ---------------- infantry ----------------
   Every other thing on the map — workers, tanks, farms, trees, ships — comes
   from Quaternius' stylised CC0 packs. Infantry was the one exception: it used
   the Mixamo "Vanguard" from the three.js examples, a semi-realistic character
   in muddy browns. Put a Vanguard rifleman next to a Quaternius worker in the
   same frame and the game reads as an asset flip, because it was: two art
   styles, two levels of stylisation, two palettes.
   The Toon Shooter soldier was already loaded (it is where the rifles came
   from), so this is a swap, not an import. The Vanguard survives as a fallback
   for the case where the Quaternius pack fails to load. */
function makeSoldierRig(teamColor, opts = {}) {
  const stylised = makeCharacterRig('soldier', teamColor, opts);
  if (stylised) return stylised;

  const rig = makeCharacterRig('infantry', teamColor, opts);
  if (!rig) return null;
  // Reuse authored weapons and attach to the hand, following locomotion.
  const weapons = MODELS.loaded.get('character:soldier');
  const name = opts.weapon === 'launcher' ? 'RocketLauncher' : opts.weapon === 'sniper' ? 'Sniper_2' : 'AK';
  const source = weapons?.scene.getObjectByName(name);
  const hand = rig.getObjectByName('mixamorigRightHand') || rig.getObjectByName('mixamorig:RightHand');
  if (source && hand) {
    const weapon = source.clone(true);
    weapon.visible = true;
    weapon.position.set(0, 0, 0); weapon.rotation.set(0, 0, 0); weapon.scale.setScalar(1);
    const size = new THREE.Box3().setFromObject(weapon).getSize(new THREE.Vector3());
    if (size.x > size.z && size.x > size.y) weapon.rotation.y = Math.PI / 2;
    else if (size.y > size.z) weapon.rotation.x = Math.PI / 2;
    normalizeModel(weapon, opts.weapon === 'launcher' ? 1.35 : 1.05);
    cloneAuthoredMaterials(weapon);
    rig.add(weapon);
    rig.updateMatrixWorld(true);
    const grip = hand.getWorldPosition(new THREE.Vector3());
    rig.worldToLocal(grip);
    weapon.position.copy(grip);
    weapon.rotation.y += Math.PI;
    weapon.rotation.x += .35;
    rig.updateMatrixWorld(true);
    hand.attach(weapon);
  }
  return rig;
}

function makeWorkerRig(teamColor, opts = {}) {
  return makeCharacterRig('worker', teamColor, opts);
}

/* ============================================================
   The Kenney city shells ship with palette UVs and no packaged texture, so
   out of the box they render as blank white blocks. We give them real
   surfaces instead: box-projected UVs generated in world units, dressed with
   the concrete / brick / trim PBR maps already in the project. Facades then
   show genuine material at a consistent scale on every building size.
   ============================================================ */
const ARCH_TEX_DIR = 'assets/models/quaternius-downtown/';
let _archMaterials = null;
function architectureMaterials() {
  if (_archMaterials) return _archMaterials;
  const loader = new THREE.TextureLoader();
  const load = (file, srgb) => {
    const t = loader.load(ARCH_TEX_DIR + file, undefined, undefined,
      () => console.warn('architecture texture missing:', file));
    t.wrapS = t.wrapT = THREE.RepeatWrapping;
    t.anisotropy = 8;
    if (srgb) t.colorSpace = THREE.SRGBColorSpace;
    return t;
  };
  // These atlases are authored dark for interior lighting; the colour term is
  // pushed well above 1.0 so facades read at daylight brightness outdoors
  // instead of collapsing into black slabs.
  const make = (base, normal, color, rough) => {
    const m = new THREE.MeshStandardMaterial({
      map: load(base, true), normalMap: load(normal, false),
      roughness: rough, metalness: 0.04,
      normalScale: new THREE.Vector2(0.6, 0.6),
    });
    m.color.setHex(color).multiplyScalar(2.4);
    return m;
  };
  _archMaterials = [
    make('T_Concrete_BaseColor.png', 'T_Concrete_Normal.png', 0xd8d5cd, 0.88),
    make('T_RedBrick_BaseColor.png', 'T_RedBrick_Normal.png', 0xc9a08c, 0.92),
    make('T_MetalConcrete_BaseColor.png', 'T_MetalConcrete_Normal.png', 0xccd2d6, 0.70),
    make('T_Trim_BaseColor.png', 'T_Trim_Normal.png', 0xc8ced2, 0.64),
  ];
  return _archMaterials;
}

/* Replace palette UVs with a box projection measured in world units. Each
   vertex picks the plane most square-on to its normal, so walls get wall
   texture and roofs get roof texture with no stretching. */
function boxProjectUVs(geometry, worldScale, unitsPerTile = 4) {
  const pos = geometry.attributes.position;
  const nrm = geometry.attributes.normal;
  if (!pos || !nrm) return;
  const uv = new Float32Array(pos.count * 2);
  const k = worldScale / unitsPerTile;
  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i) * k, y = pos.getY(i) * k, z = pos.getZ(i) * k;
    const nx = Math.abs(nrm.getX(i)), ny = Math.abs(nrm.getY(i)), nz = Math.abs(nrm.getZ(i));
    let u, v;
    if (ny >= nx && ny >= nz) { u = x; v = z; }        // roof / floor
    else if (nx >= nz) { u = z; v = y; }               // side wall
    else { u = x; v = y; }                             // front / back wall
    uv[i * 2] = u; uv[i * 2 + 1] = v;
  }
  geometry.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
}

/* Hull facade materials for the Kenney watercraft shells, which ship without
   their colormap image exactly like the city buildings did.
   Deliberately flat colour, NO map: every texture tried here (the shared
   architecture atlas, a hand-painted canvas panel texture) rendered this
   specific mesh near-black regardless of its own average brightness, while
   the identical mesh with .map stripped to null rendered correctly every
   single time (confirmed by isolating map on/off with pixel readback).
   Whatever the underlying cause, a flat PBR colour sidesteps it entirely and
   matches how the game already paints gun barrels and tank tracks. */
let _hullMaterials = null;
function hullMaterials() {
  if (_hullMaterials) return _hullMaterials;
  _hullMaterials = [
    new THREE.MeshStandardMaterial({ color: 0x8b96a0, roughness: 0.55, metalness: 0.28 }),
    new THREE.MeshStandardMaterial({ color: 0x4c5a68, roughness: 0.6, metalness: 0.18 }),
  ];
  return _hullMaterials;
}
/* Applied after makeAssetModel() for hulls that come in without a texture —
   detected generically (no map) so a future correctly-textured pack needs no
   code change here, it simply won't match and will keep its own material. */
function dressHullIfUntextured(root, seed) {
  let bare = false;
  root.traverse(o => { if (o.isMesh && !(o.material && o.material.map)) bare = true; });
  if (!bare) return;
  const palette = hullMaterials();
  const pick = palette[Math.abs(seed) % palette.length];
  root.traverse(o => {
    if (!o.isMesh || (o.material && o.material.map)) return;
    o.material = pick.clone();
    o.castShadow = true; o.receiveShadow = true;
  });
}

/* Quaternius "Animated Tanks Pack" (CC0, 4 hull variants). Every tank has a
   skinned track skeleton (needs SkeletonUtils.clone — a plain .clone() would
   share one bind pose across every tank on the field) plus two meshes,
   Tank_Turret and Tank_Gun, that sit OUTSIDE the skeleton as plain static
   nodes. We detach that pair into its own pivot group so the existing
   turret-aiming code (userData.turret) can swing them at a target exactly
   like every procedural vehicle already does. */
const TANK_VARIANTS = ['unit:tank0', 'unit:tank1', 'unit:tank2', 'unit:tank3'];
function makeTankModel(teamColor, seed = 0) {
  const variantKey = TANK_VARIANTS[Math.abs(seed) % TANK_VARIANTS.length];
  const gltf = MODELS.loaded.get(variantKey);
  if (!gltf) return null;
  let model;
  try { model = THREE.SkeletonUtils.clone(gltf.scene); } catch (e) { return null; }

  // the pack's barrel points local -X; the rest of the game's vehicles all
  // face local +X, which is what the default faceOffset (-90°) expects
  model.rotation.y = Math.PI;
  model.updateMatrixWorld(true);

  // normalize to the same footprint as the procedural tank hull (~3.3 long)
  let bounds = new THREE.Box3().setFromObject(model);
  let size = bounds.getSize(new THREE.Vector3());
  const scale = 3.9 / Math.max(size.x, size.z, 0.001);
  model.scale.setScalar(scale);
  model.updateMatrixWorld(true);
  bounds = new THREE.Box3().setFromObject(model);
  const center = bounds.getCenter(new THREE.Vector3());
  model.position.set(model.position.x - center.x, model.position.y - bounds.min.y, model.position.z - center.z);
  model.updateMatrixWorld(true);

  const root = new THREE.Group();
  root.add(model);

  let turretMesh = null, gunMesh = null;
  model.traverse(o => {
    o.castShadow = true; o.receiveShadow = true;
    if (o.name === 'Tank_Turret') turretMesh = o;
    else if (o.name === 'Tank_Gun') gunMesh = o;
  });

  if (turretMesh) {
    const pivot = new THREE.Vector3();
    turretMesh.getWorldPosition(pivot);
    const turretGroup = new THREE.Group();
    turretGroup.position.copy(pivot);
    root.add(turretGroup);
    turretGroup.attach(turretMesh);   // Object3D#attach preserves world transform
    if (gunMesh) turretGroup.attach(gunMesh);
    // Several variants put the unanimated gun below the hull roof in their
    // bind pose. Seat the complete turret assembly on the upper hull.
    const hull = model.getObjectByName('Tank_body') || model.getObjectByName('Tank_body001');
    if (hull) {
      root.updateMatrixWorld(true);
      if (hull.isSkinnedMesh) { hull.skeleton.update(); hull.computeBoundingBox(); }
      const hullBox = new THREE.Box3().setFromObject(hull);
      const turretBox = new THREE.Box3().setFromObject(turretMesh);
      turretGroup.position.y += Math.max(0, hullBox.max.y - turretBox.min.y - .06);
    }
    root.userData.turret = turretGroup;
  }

  // restrained team-colour identification — a full repaint would erase the
  // pack's own camo/paint work, so this is a light lean only
  const tint = new THREE.Color(teamColor);
  root.traverse(o => {
    if (!o.isMesh && !o.isSkinnedMesh) return;
    const mats = Array.isArray(o.material) ? o.material : [o.material];
    const clones = mats.map(m => {
      const c = m.clone();
      if (c.color) c.color.lerp(tint, 0.10);
      return c;
    });
    o.material = Array.isArray(o.material) ? clones : clones[0];
  });

  root.userData.assetModel = true;
  root.userData.assetKey = variantKey;
  root.userData.faceOffset = -Math.PI / 2;
  const clips = gltf.animations || gltf.scene.animations || [];
  const vehicleMixer = new THREE.AnimationMixer(model), trackActions = {};
  for (const [key, suffix] of [['forward', 'Tank_Forward'], ['left', 'Tank_TurningLeft'], ['right', 'Tank_TurningRight']]) {
    const source = clips.find(clip => clip.name.endsWith(suffix));
    if (!source) continue;
    // Only drive track bones. The turret remains under combat control and
    // authored root transforms must not undo placement or model scaling.
    const tracks = [];
    for (const track of source.tracks) {
      if (!track.name.startsWith('TankTrack')) continue;
      const split = track.name.lastIndexOf('.'), boneName = track.name.slice(0, split);
      // FBX inserts identity child bones with the same name for each skin.
      // Animate their parent only: the children inherit its world transform.
      model.traverse(bone => {
        if (!bone.isBone || bone.name !== boneName || bone.parent?.name === boneName) return;
        const bound = track.clone(); bound.name = bone.uuid + track.name.slice(split); tracks.push(bound);
      });
    }
    if (!tracks.length) continue;
    const clip = new THREE.AnimationClip(key, source.duration, tracks);
    const action = vehicleMixer.clipAction(clip); action.setEffectiveWeight(key === 'forward' ? 1 : 0).play();
    trackActions[key] = action;
  }
  if (trackActions.forward) { root.userData.vehicleMixer = vehicleMixer; root.userData.trackActions = trackActions; }
  return root;
}

/* One authored shell per structure type, so a police station, a bank and a
   hospital are three recognisably different buildings rather than the same
   block at three sizes. `span` multiplies the gameplay footprint and `maxH`
   caps the height, which is what keeps a library from becoming a tower.
   Military structures are deliberately absent — they keep their purpose-built
   industrial geometry instead of being dressed as offices. */
const URBAN_ARCHITECTURE = {
  // seats of power — tall, formal
  hq:            { model: 'city:medium', span: 1.40, maxH: 12 },
  cityCenter:    { model: 'city:skyD', span: 1.15, maxH: 15 },
  cityHall:      { model: 'city:l',    span: 1.35, maxH: 11 },
  courthouse:    { model: 'city:m',    span: 1.30, maxH: 10 },
  // finance & media — glass towers
  bank:          { model: 'city:skyA', span: 1.10, maxH: 14 },
  tvStation:     { model: 'city:skyC', span: 1.10, maxH: 15 },
  intelAgency:   { model: 'city:skyE', span: 1.15, maxH: 15 },
  techPark:      { model: 'city:skyA', span: 1.35, maxH: 11 },
  // knowledge & care — broad institutional blocks
  university:    { model: 'city:j',    span: 1.40, maxH: 12 },
  hospital:      { model: 'city:k',    span: 1.35, maxH: 12 },
  school:        { model: 'city:e',    span: 1.30, maxH: 8 },
  library:       { model: 'city:c',    span: 1.25, maxH: 8 },
  museum:        { model: 'city:n',    span: 1.35, maxH: 10 },
  policeStation: { model: 'city:d',    span: 1.25, maxH: 8 },
  // commerce & storage — low, wide
  market:        { model: 'city:f',    span: 1.30, maxH: 8 },
  // Depots use the dedicated industrial architecture with loading doors.
  chipFab:       { model: 'city:i',    span: 1.30, maxH: 10 },
  // housing — from walk-ups to towers
  housing:       { model: 'city:a',    span: 1.25, maxH: 9 },
  residential:   { model: 'city:g',    span: 1.35, maxH: 11 },
  apartments:    { model: 'city:i',    span: 1.15, maxH: 17 },
  villageCenter: { model: 'city:c',    span: 1.20, maxH: 7 },
};

/* Returns a complete, textured city building sized to the gameplay footprint. */
function makeDowntownBuilding(buildingKey, teamColor, seed = 0) {
  if (['workerHouse', 'cottage', 'luxuryVillas'].includes(buildingKey)) {
    const variants = buildingKey === 'luxuryVillas' ? ['c', 'd'] : ['a', 'b', 'c', 'd'];
    const variant = variants[Math.abs(seed) % variants.length];
    const gltf = MODELS.loaded.get(`suburban:${variant}`);
    if (gltf) {
      const model = gltf.scene.clone(true);
      cloneAuthoredMaterials(model, teamColor, 0.025);
      styleExternalArchitecture(model, 'suburban', seed);
      normalizeModel(model, BUILDINGS[buildingKey].size * 1.32, buildingKey === 'luxuryVillas' ? 5.6 : 4.8);
      model.rotation.y = (seed % 4) * Math.PI * 0.5;
      const root = new THREE.Group();
      root.add(model);
      root.userData.assetModel = true;
      root.userData.assetKey = `suburban:${variant}`;
      return root;
    }
  }

  if (buildingKey === 'farm') {
    const barnAsset = MODELS.loaded.get('farm:barn');
    const siloAsset = MODELS.loaded.get('farm:siloHouse');
    if (barnAsset && siloAsset) {
      const root = new THREE.Group();
      const barn = barnAsset.scene.clone(true);
      cloneAuthoredMaterials(barn);
      styleExternalArchitecture(barn, 'farm', seed);
      normalizeModel(barn, 5.8, 4.8);
      barn.position.x -= 1.45;
      barn.rotation.y = (seed % 2) * Math.PI;
      root.add(barn);

      const silo = siloAsset.scene.clone(true);
      cloneAuthoredMaterials(silo);
      styleExternalArchitecture(silo, 'farm', seed + 1);
      normalizeModel(silo, 3.25, 4.9);
      silo.position.set(3.15, 0, -0.55);
      silo.rotation.y = Math.PI * 0.5;
      root.add(silo);

      const soil = new THREE.Mesh(new THREE.BoxGeometry(8.8, .08, 2), new THREE.MeshStandardMaterial({ color: 0x554331, roughness: 1 }));
      soil.position.set(0, .05, 3.9); soil.receiveShadow = true; root.add(soil);
      const cropMaterial = new THREE.MeshStandardMaterial({ color: 0x737b3d, roughness: .95 });
      for (let row = 0; row < 5; row++) {
        const crops = new THREE.Mesh(new THREE.BoxGeometry(8.4, .16, .18), cropMaterial);
        crops.position.set(0, .16, 3.15 + row * .36); crops.receiveShadow = true; root.add(crops);
      }

      root.userData.assetModel = true;
      root.userData.assetKey = 'farm:complex';
      return root;
    }
  }

  const spec = URBAN_ARCHITECTURE[buildingKey];
  if (!spec || !BUILDINGS[buildingKey]) return null;

  const gltf = MODELS.loaded.get(spec.model);
  if (!gltf) return null;
  const model = gltf.scene.clone(true);
  const targetSpan = BUILDINGS[buildingKey].size * spec.span;
  normalizeModel(model, targetSpan, spec.maxH);

  // dress the untextured shell: pick a facade material per structure so a
  // brick school and a concrete bank never read as the same white block
  const palette = architectureMaterials();
  const pick = palette[Math.abs(seed * 2654435761 + buildingKey.length * 97) % palette.length];
  const worldScale = model.scale.x || 1;
  const materialCopies = new Map();
  model.traverse(o => {
    if (!o.isMesh) return;
    o.castShadow = true;
    o.receiveShadow = true;
    const authored = Array.isArray(o.material) ? o.material : [o.material];
    if (authored.every(m => m.map)) {
      const copies = authored.map(src => {
        if (materialCopies.has(src)) return materialCopies.get(src);
        const m = src.clone();
        m.roughness = Math.max(.65, m.roughness ?? .8);
        m.metalness = Math.min(.25, m.metalness ?? 0);
        m.envMapIntensity = .65;
        materialCopies.set(src, m);
        return m;
      });
      o.material = Array.isArray(o.material) ? copies : copies[0];
      return;
    }
    o.geometry = o.geometry.clone();
    boxProjectUVs(o.geometry, worldScale, 4.5);
    const m = pick.clone();
    // gentle per-building tint drift so a row of the same type still varies
    const jitter = (((seed * 1103515245 + 12345) >>> 0) % 1000) / 1000;
    m.color.multiplyScalar(0.92 + jitter * 0.2); // vary brightness, never darken to black
    o.material = m;
  });
  // only quarter turns: authored facades keep their intended front elevation
  model.rotation.y = (seed % 4) * Math.PI * 0.5;

  const root = new THREE.Group();
  root.add(model);
  root.userData.assetModel = true;
  root.userData.assetKey = spec.model;

  // Restrained national identifier: a real building keeps its original brick,
  // stone and metal instead of being painted wholesale in the team colour.
  const plaqueMat = new THREE.MeshStandardMaterial({
    color: teamColor, roughness: 0.42, metalness: 0.18,
    emissive: new THREE.Color(teamColor).multiplyScalar(0.08),
  });
  const plaque = new THREE.Mesh(new THREE.BoxGeometry(1.15, 0.14, 0.55), plaqueMat);
  plaque.position.set(targetSpan * 0.3, 0.18, targetSpan * 0.36);
  plaque.castShadow = true;
  root.add(plaque);
  return root;
}
