extends Node3D
## Positional battle sound for the native world.
## Sounds come from res://audio (generated by tools/make-sounds.gd; any file can
## be replaced by a recording of the same name). One-shots play from a pool of
## 3D players; the listener sits on the ground at the camera focus, because an
## RTS camera is too high for natural distance fall-off. Distant sounds are
## quieter and muffled by the players' attenuation filter. An "SFX" bus adds a
## little open-air reverb and a limiter keeps many explosions from clipping.

const POOL_SIZE := 32
const VARIANTS := {"rifle": 3, "explosion": 2, "impact": 2}

var _streams := {}
var _pool: Array[AudioStreamPlayer3D] = []
var _next := 0
var _listener: AudioListener3D
var _wind: AudioStreamPlayer
var _surf: AudioStreamPlayer3D
var _recent := {}  # name -> times played this frame, to cap stacked rifles

func _ready() -> void:
	_setup_buses()
	for name in ["cannon", "engine_loop", "wind_loop", "surf_loop"]:
		_streams[name] = load("res://audio/%s.wav" % name)
	for name in VARIANTS:
		for i in range(VARIANTS[name]):
			_streams["%s_%d" % [name, i + 1]] = load("res://audio/%s_%d.wav" % [name, i + 1])
	for i in range(POOL_SIZE):
		var p := AudioStreamPlayer3D.new()
		p.bus = "SFX"
		p.max_distance = 420.0
		p.attenuation_filter_cutoff_hz = 3200.0
		p.attenuation_filter_db = -20.0
		add_child(p)
		_pool.append(p)
	_listener = AudioListener3D.new()
	add_child(_listener)
	_listener.make_current()
	_wind = AudioStreamPlayer.new()
	_wind.stream = _streams.wind_loop
	_wind.volume_db = -22.0
	_wind.bus = "SFX"
	add_child(_wind)
	_wind.play()
	_surf = AudioStreamPlayer3D.new()
	_surf.stream = _streams.surf_loop
	_surf.unit_size = 30.0
	_surf.max_distance = 260.0
	_surf.volume_db = -8.0
	_surf.bus = "SFX"
	add_child(_surf)
	_surf.play()

func _setup_buses() -> void:
	if AudioServer.get_bus_index("SFX") != -1:
		return
	AudioServer.add_bus()
	var sfx := AudioServer.bus_count - 1
	AudioServer.set_bus_name(sfx, "SFX")
	AudioServer.set_bus_send(sfx, "Master")
	# Headroom: a firefight should rarely touch the limiter, or it sounds squashed.
	AudioServer.set_bus_volume_db(sfx, -4.0)
	var reverb := AudioEffectReverb.new()
	reverb.room_size = 0.55
	reverb.damping = 0.6
	reverb.wet = 0.12
	reverb.dry = 1.0
	AudioServer.add_bus_effect(sfx, reverb)
	var limiter := AudioEffectHardLimiter.new()
	limiter.ceiling_db = -1.0
	AudioServer.add_bus_effect(0, limiter)

## Plays a one-shot at a world position. `size` scales how far it carries.
func play(name: String, at: Vector3, volume_db := 0.0, size := 1.0) -> void:
	# Many rifles firing in the same frame blend into one louder report.
	var count: int = _recent.get(name, 0)
	if count >= 4:
		return
	_recent[name] = count + 1
	var key: String = name
	if VARIANTS.has(name):
		key = "%s_%d" % [name, randi_range(1, VARIANTS[name])]
	var p := _pool[_next]
	_next = (_next + 1) % POOL_SIZE
	p.stream = _streams[key]
	p.unit_size = 14.0 * size
	p.volume_db = volume_db
	p.pitch_scale = randf_range(0.9, 1.08)
	p.global_position = at
	p.play()

## A looping engine for a vehicle; call engine_update() as it drives.
func add_engine(parent: Node3D) -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	p.stream = _streams.engine_loop
	p.bus = "SFX"
	p.unit_size = 10.0
	p.max_distance = 180.0
	p.volume_db = -16.0
	p.pitch_scale = randf_range(0.9, 1.0)
	parent.add_child(p)
	p.play(randf() * 1.5)
	return p

func engine_update(engine: AudioStreamPlayer3D, moving: bool, delta: float) -> void:
	var loud := -6.0 if moving else -16.0
	var pitch := 1.12 if moving else 0.88
	engine.volume_db = lerpf(engine.volume_db, loud, minf(1.0, delta * 2.0))
	engine.pitch_scale = lerpf(engine.pitch_scale, pitch, minf(1.0, delta * 1.5))

## Listener on the ground at the camera focus, facing the camera's way.
## `coast` is the nearest shoreline point, where the surf plays from.
func follow(focus: Vector3, camera: Camera3D, coast: Vector3) -> void:
	_recent.clear()
	_listener.global_transform = Transform3D(camera.global_basis, focus + Vector3.UP * 2.0)
	_surf.global_position = coast
