extends Node3D
## Positional battle sound for the native world.
## Sounds come from res://audio (generated by tools/make-sounds.gd; any file can
## be replaced by a recording of the same name). One-shots play from a pool of
## 3D players; the listener sits on the ground at the camera focus, because an
## RTS camera is too high for natural distance fall-off. Distant sounds are
## quieter and muffled by the players' attenuation filter. An "SFX" bus adds a
## little open-air reverb and a limiter keeps many explosions from clipping.

const POOL_SIZE := 32
const VARIANTS := {"rifle": 3, "explosion": 2, "impact": 2}

var _streams := {}
var _pool: Array[AudioStreamPlayer3D] = []
var _next := 0
var _listener: AudioListener3D
var _wind: AudioStreamPlayer
var _surf: AudioStreamPlayer3D
var _music: AudioStreamPlayer
var _battle_music: AudioStreamPlayer
var _battle_hold := 0.0
var _battle_mix := 0.0
var _focus := Vector3.ZERO
var _click: AudioStreamPlayer
var _feedback: AudioStreamPlayer
var _cues := {}
var _recent := {}  # name -> times played this frame, to cap stacked rifles

func _ready() -> void:
	_setup_buses()
	for name in ["cannon", "engine_loop", "wind_loop", "surf_loop"]:
		_streams[name] = load("res://audio/%s.wav" % name)
	for name in VARIANTS:
		for i in range(VARIANTS[name]):
			_streams["%s_%d" % [name, i + 1]] = load("res://audio/%s_%d.wav" % [name, i + 1])
	for i in range(POOL_SIZE):
		var p := AudioStreamPlayer3D.new()
		p.bus = "SFX"
		p.max_distance = 420.0
		p.attenuation_filter_cutoff_hz = 3200.0
		p.attenuation_filter_db = -20.0
		add_child(p)
		_pool.append(p)
	_listener = AudioListener3D.new()
	add_child(_listener)
	_listener.make_current()
	_wind = AudioStreamPlayer.new()
	_wind.stream = _streams.wind_loop
	_wind.volume_db = -22.0
	_wind.bus = "SFX"
	add_child(_wind)
	_wind.play()
	_surf = AudioStreamPlayer3D.new()
	_surf.stream = _streams.surf_loop
	_surf.unit_size = 30.0
	_surf.max_distance = 260.0
	_surf.volume_db = -8.0
	_surf.bus = "SFX"
	add_child(_surf)
	_surf.play()
	# Music (tools/make-music.gd): a quiet theme under the whole session, on its own bus.
	_music = AudioStreamPlayer.new()
	_music.stream = load("res://audio/music_loop.wav")
	_music.bus = "Music"
	_music.volume_db = -9.0
	_music.process_mode = Node.PROCESS_MODE_ALWAYS   # it keeps playing in the pause menu
	add_child(_music)
	_music.play()
	_battle_music = AudioStreamPlayer.new()
	_battle_music.stream = load("res://audio/battle_loop.wav")
	_battle_music.bus = "Music"
	_battle_music.volume_db = -80.0
	_battle_music.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(_battle_music)
	_battle_music.play()
	# A soft click on every button, wherever it is (the interface used to be silent).
	_click = AudioStreamPlayer.new()
	_click.stream = load("res://audio/ui_click.wav")
	_click.bus = "Interface"
	_click.volume_db = -14.0
	_click.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(_click)
	_feedback = AudioStreamPlayer.new()
	_feedback.bus = "Interface"
	_feedback.volume_db = -14.0
	_feedback.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(_feedback)
	for cue in ["ready", "accepted", "rejected", "counter"]:
		_cues[cue] = _cue(cue)
	get_tree().node_added.connect(_on_node_added)
	for b in get_tree().root.find_children("*", "BaseButton", true, false):
		_on_node_added(b)

func _on_node_added(node: Node) -> void:
	if node is BaseButton and not node.has_meta("clicks"):
		node.set_meta("clicks", true)
		node.pressed.connect(_play_click)

func _play_click() -> void:
	if _click != null and is_instance_valid(_click):
		_click.play()

func _setup_buses() -> void:
	for extra in ["Music", "Interface"]:
		if AudioServer.get_bus_index(extra) == -1:
			AudioServer.add_bus()
			AudioServer.set_bus_name(AudioServer.bus_count - 1, extra)
			AudioServer.set_bus_send(AudioServer.bus_count - 1, "Master")
	if AudioServer.get_bus_index("SFX") != -1:
		return
	AudioServer.add_bus()
	var sfx := AudioServer.bus_count - 1
	AudioServer.set_bus_name(sfx, "SFX")
	AudioServer.set_bus_send(sfx, "Master")
	# Headroom: a firefight should rarely touch the limiter, or it sounds squashed.
	AudioServer.set_bus_volume_db(sfx, -4.0)
	var reverb := AudioEffectReverb.new()
	reverb.room_size = 0.55
	reverb.damping = 0.6
	reverb.wet = 0.12
	reverb.dry = 1.0
	AudioServer.add_bus_effect(sfx, reverb)
	var limiter := AudioEffectHardLimiter.new()
	limiter.ceiling_db = -1.0
	AudioServer.add_bus_effect(0, limiter)

## Plays a one-shot at a world position. `size` scales how far it carries.
func play(name: String, at: Vector3, volume_db := 0.0, size := 1.0) -> void:
	if name in ["rifle", "cannon", "explosion"] and at.distance_to(_focus) < 240.0:
		_battle_hold = 18.0
	# Many rifles firing in the same frame blend into one louder report.
	var count: int = _recent.get(name, 0)
	if count >= 4:
		return
	_recent[name] = count + 1
	var key: String = name
	if VARIANTS.has(name):
		key = "%s_%d" % [name, randi_range(1, VARIANTS[name])]
	var p := _pool[_next]
	_next = (_next + 1) % POOL_SIZE
	p.stream = _streams[key]
	p.unit_size = 14.0 * size
	p.volume_db = volume_db
	p.pitch_scale = randf_range(0.9, 1.08)
	p.global_position = at
	p.play()

## A looping engine for a vehicle; call engine_update() as it drives.
func add_engine(parent: Node3D) -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	p.stream = _streams.engine_loop
	p.bus = "SFX"
	p.unit_size = 10.0
	p.max_distance = 180.0
	p.volume_db = -16.0
	p.pitch_scale = randf_range(0.9, 1.0)
	parent.add_child(p)
	p.play(randf() * 1.5)
	return p

func engine_update(engine: AudioStreamPlayer3D, moving: bool, delta: float) -> void:
	var loud := -6.0 if moving else -16.0
	var pitch := 1.12 if moving else 0.88
	engine.volume_db = lerpf(engine.volume_db, loud, minf(1.0, delta * 2.0))
	engine.pitch_scale = lerpf(engine.pitch_scale, pitch, minf(1.0, delta * 1.5))

## Listener on the ground at the camera focus, facing the camera's way.
## `coast` is the nearest shoreline point, where the surf plays from.
func follow(focus: Vector3, camera: Camera3D, coast: Vector3) -> void:
	_focus = focus
	_recent.clear()
	_listener.global_transform = Transform3D(camera.global_basis, focus + Vector3.UP * 2.0)
	_surf.global_position = coast

## Real-time crossfade, independent of 1×/4× simulation speed. Music mute and
## volume still come from the shared Music bus; no player setting is changed.
func _process(delta: float) -> void:
	delta /= maxf(Engine.time_scale, 0.001)
	_battle_hold = maxf(0.0, _battle_hold - delta)
	_battle_mix = move_toward(_battle_mix, 1.0 if _battle_hold > 0.0 else 0.0, delta / 6.0)
	if _music != null and _battle_music != null:
		_music.volume_db = linear_to_db(maxf(0.0001, (1.0 - _battle_mix) * db_to_linear(-9.0)))
		_battle_music.volume_db = linear_to_db(maxf(0.0001, _battle_mix * db_to_linear(-12.0)))

func diplomatic_feedback(kind: String) -> void:
	if _feedback != null and _cues.has(kind):
		_feedback.stream = _cues[kind]
		_feedback.play()

static func _cue(kind: String) -> AudioStreamWAV:
	var rate := 22050
	var data := PackedByteArray()
	data.resize(int(rate * 0.32) * 2)
	var pitches: Array = {"ready": [440.0, 554.37], "accepted": [523.25, 659.25], "rejected": [392.0, 293.66], "counter": [440.0, 493.88]}[kind]
	for i in range(data.size() / 2):
		var t := float(i) / rate
		var age := fmod(t, 0.16)
		var env := smoothstep(0.0, 0.008, age) * exp(-age * 24.0) * (1.0 - smoothstep(0.12, 0.16, age))
		data.encode_s16(i * 2, int(sin(TAU * float(pitches[mini(1, int(t / 0.16))]) * age) * env * 8000.0))
	var wav := AudioStreamWAV.new()
	wav.format = AudioStreamWAV.FORMAT_16_BITS
	wav.mix_rate = rate
	wav.data = data
	return wav
